name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
      - ElManchacho/issue45
jobs:
  build_and_deploy_on_merge:    
    runs-on: ubuntu-latest
    steps:
      - name: Update version
        run: node .github/workflows/version-update.js --currentVersion $FRONT_VERSION --tokenVersion '${{ secrets.GET_VERSION_TOKEN }}'