name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  gitleaks-scan:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Gitleaks
        run: |
          wget https://github.com/zricethezav/gitleaks/releases/download/v7.2.0/gitleaks-linux-amd64
          chmod +x gitleaks-linux-amd64
          sudo mv gitleaks-linux-amd64 /usr/local/bin/gitleaks
      - name: Run Gitleaks
        run: gitleaks --path=${{ github.workspace }}
  build_and_deploy_on_merge:    
    needs:
      - gitleaks-scan
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: obing-dev/package-lock.json
      - name: Install dependencies
        run: |
          cd obing-dev
          npm ci
      - name: Firestore package correction
        run: node .github/workflows/package-patcher.js
      - name: Update version
        run: node .github/workflows/version-update.js --currentVersion ${{ vars.FRONT_VERSION }} --tokenVersion '${{ secrets.GET_VERSION_TOKEN }}'
      - name: Build
        run: |
          cd obing-dev
          npm run build
      - name: Firebase hosting deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: obing-dev/
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_O_BING }}'
          channelId: live
          projectId: o-bing