name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: obing-dev/package-lock.json
      - name: Install dependencies
        run: |
          cd obing-dev
          npm install
      - name: Firestore package correction
        run: node .github/workflows/package-patcher.js
      - name: Build
        run: |
          cd obing-dev
          npm run build

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:o-bing-pld
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
